spring:
  application:
    name: medical-agent-bot-bff

  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.qdrant.QdrantVectorStoreAutoConfiguration
      - org.springframework.ai.autoconfigure.openai.OpenAiEmbeddingAutoConfiguration  # stop OpenAI embedding bean

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1
      chat:
        model: llama-3.1-8b-instant
        max-completion-tokens: 300
        temperature: 0.3

    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        temperature: 0.3

    vectorstore:
      qdrant:
        host: ${QDRANT_URL:localhost}
        port: 6334
        collection-name: medical-agent-rag
        use-tls: true
        api-key: ${QDRANT_API_KEY}
        initialize-schema: true

medicalai:
  jina:
    api-key: ${JINA_API_KEY}
    base-url: https://api.jina.ai
    model: jina-embeddings-v5-text-small
    dimensions: 1024
    task: retrieval.query

logging:
  level:
    com.vamshi.medicalagentbot: INFO
    org.springframework.ai: warn